#!/bin/bash
echo "*** THIS DELETES ALL BFORMS DATA. CANCEL NOW TO SAVE YOUR DATA! ***"
echo -n "... 10 seconds "
sleep 5 
echo -n "... 5 seconds "
sleep 4 
echo -n "... 1 second "
sleep 1
source ../../apps/forms/settings.py
psql -t -d $BFORMS_DATABASE_NAME -c "SELECT 'DROP TABLE ' || n.nspname || '.' || c.relname || ' CASCADE;' FROM pg_catalog.pg_class AS c LEFT JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace WHERE relkind = 'r' AND n.nspname NOT IN ('pg_catalog', 'pg_toast') AND pg_catalog.pg_table_is_visible(c.oid)" >/tmp/droptables
psql -d $BFORMS_DATABASE_NAME -f /tmp/droptables
mv $BDB_PATH/DB_CONFIG /tmp
touch $BDB_PATH/foo
rm -rf $BDB_PATH/*
mv /tmp/DB_CONFIG $BDB_PATH
echo "  ... Deleted Everything."
