# -*- coding: utf-8 -*-

import forms.form_models.bfsql as bfsql
import forms.form_models.bform as bforms
from forms.form_models.bfbdb import *

bf = bforms.BerkeleyForm()
bf.theme='default'
bf.doctype='html'

qdb = [
	{'type':'Text','label':'YOUR NAME'},
	{'type':'Text','label':'Today\'s Date'},
	{'type':'Text','label':'Physician\'s Name'},
	{'type':'Text','label':'Phone #'},
	{'type':'Text','label':'When was your last visit to your physician?'},
	{'type':'Text','label':'When was yourl ast complete physical?' },
	{'type':'Section','label':'Medical History','style':'section'},
		{'type':'CheckMany','label':'Please tell us if you have had any of the following by checking the appropriate box: ',
		'choices':(
		'Bacterial Endocarditis ',
		'Heart Murmur',
		'Irregular Heart Beat',
		'High Blood Pressure',
		'Low Blood Pressure ',
		'Rheumatic Heart Fever',
		'Rheumatic Heart Disease ',
		'Artificial Heart Valves',
		'Congenital Heart Lesion',
		'Mitral Valve Prolapse',
		'Heart Attack  _____ year',
		'Angina/ Chest Pain ',
		'Heart Pacemaker ',
		'Heart Surgery',
		'Congestive Heart Failure',
		'Hemophelia',
		'Blood Disease ',
		'Sickle Cell Anemia',
		'Anemia / Blood Problems ',
		'Excessive Bleeding',
		'Asthma',
		'Respiratory Disease',
		'Shortness of Breath',
		'Hay Fever',
		'Sinus Problems',
		'Tuberculosis',
		'Eye Disorders / Glaucoma',
		'AIDS',
		'Immunosupressive Disorders / ARC',
		'Any Artificial Replacement Artificial Knee, Hip, Joint, Pins, Plate',
		'Rheumatism / Arthritis',
		'Neurological Problems',
		'Epilepsy / Seizures',
		'Psychiatric Problems',
		'Emotional Problems',
		'Alcoholism',
		'Chemical Dependency',
		'Drug Addiction',
		'Malignancies',
		'Cancers, Tumors, Growths',
		'Radiation Treatments',
		'Diabetes',
		'Kidney Problems',
		'Dialysis',
		'Liver Problems',
		'Hepatitis',
		'Stroke',
		'Thyroid Problems',
		'Ulcer / Colitis',
		'Venereal Disease',
		'Herpes',
		'Fever Blisters',
		'Pregnant  ____ months',
		'Oral Contraceptives',
		)},
		{'type':'Text','label':'Please list any ALLERGIES to Drugs, Medications or Anesthetics:'},
		{'type':'Text','label':'Please list any other MEDICAL CONDITIONS not mentioned above:'},
		{'type':'Text','label':'Please list all DRUGS/MEDICATIONS that you currently take:(Include the dosage and frequency that you are on)'},
	{'type':'CloseTag'},
	{'type':'Section','label':'DENTAL History','style':'section'},
		{'type':'Text','label':'Please describe your chief oral complaint:'},
		{'type':'Section','label':'Are your teeth sensitive to :','style':'subsection'},
			{'type':'CheckOne','label':'Heat?','choices':('Yes','No') },
			{'type':'CheckOne','label':'Cold?','choices':('Yes','No') },
			{'type':'CheckOne','label':'Sweets?','choices':('Yes','No') },
			{'type':'CheckOne','label':'Chewing?','choices':('Yes','No')},
		{'type':'CloseTag'},
		{'type':'CheckOne','label':'Do you have any food traps?','choices':('Yes','No') },
		{'type':'CheckOne','label':'Do your gums ever feel tender or swollen?','choices':('Yes','No') },
		{'type':'CheckOne','label':'Do your gums bleed when brushing? ','choices':('Yes','No') },
		{'type':'CheckOne','label':'Do you have any teeth that feel loose? ','choices':('Yes','No') },
		{'type':'CheckOne','label':'Have you  ever been treated for periodontal disease or pyorrhea? ','choices':('Yes','No') },
		{'type':'CheckOne','label':'Do you use dental floss? ','choices':('Yes','No') } ,
		{'type':'CheckOne','label':'Have you had any previous injuries to your face or jaws?','choices':('Yes','No') } ,
		{'type':'CheckOne','label':'Do you lose or break fillings?','choices':('Yes','No') } ,
		{'type':'CheckOne','label':'Do you clench or grind your teeth?','choices':('Yes','No') } ,
		{'type':'CheckOne','label':'Do you seem to strike some teeth before others when closing?','choices':('Yes','No') } ,
		{'type':'CheckOne','label':'Have you ever had your bite adjusted? ','choices':('Yes','No') },
		{'type':'CheckOne','label':'Do your jaws ever feel tired or ache? ','choices':('Yes','No') },
		{'type':'CheckOne','label':'Do your jaws ever feel tired or ache?','choices':('Yes','No') },
		{'type':'CheckOne','label':'Can you chew comfortably on both sides of your mouth?','choices':('Yes','No') },
		{'type':'CheckOne','label':'Have you had a complete dental examination,','choices':('Yes','No') },
		{'type':'CheckOne','label':'including full mouth x-rays, in the past 3 years?','choices':('Yes','No') } ,
		{'type':'CheckOne','label':'Have you had your teeth cleaned regularly?','choices':('Yes','No') },
		{'type':'Text','label':'When was your last cleaning?'},
		
		{'type':'CheckOne','label':'Do you have all or most of your natural teeth?','choices':('Yes','No') },
		{'type':'CheckOne','label':'Would you like to keep your natural teeth?','choices':('Yes','No') },
		{'type':'CheckOne','label':'If you\'ve had teeth removed, have they been replaced?','choices':('Yes','No') },
		{'type':'Text','label':'If you could improve your teeth or smile, what would you do?'},
	
		{'type':'CheckOne','label':'Do you consider yourself a nervous dental patient?','choices':('Yes','No') },
		{'type':'CheckOne','label':'Have you ever had an unpleasant dental experience?','choices':('Yes','No') },
		{'type':'Text','label':'When was your last dental appointment?'},
		{'type':'Text','label':'What was done at that visit?'},
		{'type':'Text','label':'Where was it done?'},
		{'type':'CheckOne','label':'Have you ever experienced problems with novocaine?','choices':('Yes','No') },
		
	{'type':'CloseTag'},
	
	
	{'type':'Section','label':'Medical History Update','style':'section'},
		{'type':'CheckMany','label':'Please tell us if you have had any of the following by checking the appropriate box: ',
		'choices':(
		'Bacterial Endocarditis ',
		'Heart Murmur',
		'Irregular Heart Beat',
		'High Blood Pressure',
		'Low Blood Pressure ',
		'Rheumatic Heart Fever',
		'Rheumatic Heart Disease ',
		'Artificial Heart Valves',
		'Congenital Heart Lesion',
		'Mitral Valve Prolapse',
		'Heart Attack  _____ year',
		'Angina/ Chest Pain ',
		'Heart Pacemaker ',
		'Heart Surgery',
		'Congestive Heart Failure',
		'Hemophelia',
		'Blood Disease ',
		'Sickle Cell Anemia',
		'Anemia / Blood Problems ',
		'Excessive Bleeding',
		'Asthma',
		'Respiratory Disease',
		'Shortness of Breath',
		'Hay Fever',
		'Sinus Problems',
		'Tuberculosis',
		'Eye Disorders / Glaucoma',
		'AIDS',
		'Immunosupressive Disorders / ARC',
		'Any Artificial Replacement Artificial Knee, Hip, Joint, Pins, Plate',
		'Rheumatism / Arthritis',
		'Neurological Problems',
		'Epilepsy / Seizures',
		'Psychiatric Problems',
		'Emotional Problems',
		'Alcoholism',
		'Chemical Dependency',
		'Drug Addiction',
		'Malignancies',
		'Cancers, Tumors, Growths',
		'Radiation Treatments',
		'Diabetes',
		'Kidney Problems',
		'Dialysis',
		'Liver Problems',
		'Hepatitis',
		'Stroke',
		'Thyroid Problems',
		'Ulcer / Colitis',
		'Venereal Disease',
		'Herpes',
		'Fever Blisters',
		'Pregnant  ____ months',
		'Oral Contraceptives',
		)},
		{'type':'Text','label':'Please list any ALLERGIES to Drugs, Medications or Anesthetics:'},
		{'type':'Text','label':'Please list any other MEDICAL CONDITIONS not mentioned above:'},
		{'type':'Text','label':'Please list all DRUGS/MEDICATIONS that you currently take:(Include the dosage and frequency that you are on)'},
	{'type':'CloseTag'},
	{'type':'Text','label':'Patient Signature'},
	{'type':'Text','label':'Date'},
	]

bforms.createQuestions(bf,qdb)
saveObject(bf)
